// This is an independent project of an individual developer. Dear PVS-Studio, please check it.
// PVS-Studio Static Code Analyzer for C, C++, C#, and Java: http://www.viva64.com

// ------------------------------------------------------------
// This code is automatically generated by GrammarTreeParser
// ------------------------------------------------------------

#include "GrammarTree.h"

#include "common.h"

using Node = GrammarTree::Node;
using NodeType = Node::Type;
using TokenType = Token::TokenType;
using StatementType = Statement::Type;

static constexpr usize emptyBranchStartIndex = 0;
static constexpr usize exitBranchStartIndex = 1;
static constexpr usize assignBranchStartIndex = 4;

GrammarTree::GrammarTree()
{
	_nodes.reserve(8);

	_nodes = {
		// EMPTY BRANCH - index 0
		Node{ NodeType::TOKEN, TokenType::SEMICOLON },

		// EXIT BRANCH - index 1
		Node{ NodeType::TOKEN, TokenType::EXIT },
		Node{ NodeType::EXPRA, TokenType::NONE },
		Node{ NodeType::TOKEN, TokenType::SEMICOLON },

		// ASSIGN BRANCH - index 4
		Node{ NodeType::TOKEN, TokenType::VARIABLE },
		Node{ NodeType::TOKEN, TokenType::EQUALS },
		Node{ NodeType::EXPRA, TokenType::NONE },
		Node{ NodeType::TOKEN, TokenType::SEMICOLON } 
	};

	branches = {
		Branch{ StatementType::EMPTY, &_nodes[emptyBranchStartIndex] },
		Branch{ StatementType::EXIT, &_nodes[exitBranchStartIndex] },
		Branch{ StatementType::ASSIGN, &_nodes[assignBranchStartIndex] },
	};

	// EMPTY BRANCH
	usize start = emptyBranchStartIndex;

	// EXIT BRANCH
	start = exitBranchStartIndex;
	_nodes[start].branchingNodes.push_back(&_nodes[start + 1]);
	_nodes[start + 1].branchingNodes.push_back(&_nodes[start + 2]);

	// ASSIGN BRANCH
	start = assignBranchStartIndex;
	_nodes[start].branchingNodes.push_back(&_nodes[start + 1]);
	_nodes[start + 1].branchingNodes.push_back(&_nodes[start + 2]);
	_nodes[start + 2].branchingNodes.push_back(&_nodes[start + 3]);
}